config/routes.rb
Rails.application.routes.draw do
  resources :animals
  resources :user
  resources :application_record

  devise_scope :user do
    # Redireciona os usuários deslogados de volta para a tela de "sign-in"
    get "", to: "devise/sessions#new"
  end

devise_for :users
end

app/models/animal.rb
class Animal < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_animal, only: %i[ show edit update destroy ]

  # GET /animals or /animals.json
  def index
    @animals = Animal.all
  end

  # GET /animals/1 or /animals/1.json
  def show
  end

  # GET /animals/new
  def new
    @animal = Animal.new
  end

  # GET /animals/1/edit
  def edit
  end

  # POST /animals or /animals.json
  def create
    @animal = Animal.new(animal_params)

    respond_to do |format|
      if @animal.save
        format.html { redirect_to animal_url(@animal), notice: "Animal foi criado com sucesso." }
        format.json { render :show, status: :created, location: @animal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animals/1 or /animals/1.json
  def update
    respond_to do |format|
      if @animal.update(animal_params)
        format.html { redirect_to animal_url(@animal), notice: "Animal foi editado com sucesso." }
        format.json { render :show, status: :ok, location: @animal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animals/1 or /animals/1.json
  def destroy
    @animal.destroy

    respond_to do |format|
      format.html { redirect_to animals_url, notice: "Animal foi deletado com sucesso." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_animal
      @animal = Animal.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def animal_params
      params.require(:animal).permit(:criacao_do_animal, :raca, :idade_do_animal)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery
   
    #application_controller.rb
    def after_sign_in_path_for(resource_or_scope)
      if resource_or_scope.is_a?(User)
        "/animals"
      else
        super
      end
    end
  end

app/controllers/turbo_devise_controller.rb
# app/controllers/turbo_devise_controller.rb

class TurboDeviseController < ApplicationController
    class Responder < ActionController::Responder
      def to_turbo_stream
        controller.render(options.merge(formats: :html))
      rescue ActionView::MissingTemplate => error
        if get?
          raise error
        elsif has_errors? && default_action
          render rendering_options.merge(formats: :html, status: :unprocessable_entity)
        else
          redirect_to navigation_location
        end
      end
    end
  
    self.responder = Responder
    respond_to :html, :turbo_stream
  end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/animals/_animal.html.erb
<div id="<%= dom_id animal %>">
  <p>
    <strong>Criacao do animal:</strong>
    <%= animal.criacao_do_animal %>
  </p>

  <p>
    <strong>Raca:</strong>
    <%= animal.raca %>
  </p>

  <p>
    <strong>Idade do animal:</strong>
    <%= animal.idade_do_animal %>
  </p>

</div>

app/views/animals/_form.html.erb
<%= form_with(model: animal) do |form| %>
  <% if animal.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(animal.errors.count, "error") %> "Animal" não foi salvo:</h2>

      <ul>
        <% animal.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :criacao_do_animal, style: "display: block" %>
    <%= form.text_field :criacao_do_animal %>
  </div>

  <div>
    <%= form.label :raca, style: "display: block" %>
    <%= form.text_field :raca %>
  </div>

  <div>
    <%= form.label :idade_do_animal, style: "display: block" %>
    <%= form.number_field :idade_do_animal %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/animals/edit.html.erb
<h1>Editar "Animal"</h1>

<%= render "form", animal: @animal %>

<br>

<div>
  <%= link_to "Mostrar 'animal'", @animal %> |
  <%= link_to "Voltar para 'animais'", animals_path %>
</div>

app/views/animals/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Animais</h1>

<div id="animals">
  <% @animals.each do |animal| %>
    <%= render animal %>
    <p>
      <%= link_to "Exibir animal", animal %>
    </p>
  <% end %>
</div>

<%= link_to "Novo animal", new_animal_path %>

app/views/animals/new.html.erb
<h1>Novo "animal"</h1>

<%= render "form", animal: @animal %>

<br>

<div>
  <%= link_to "Voltar para animais", animals_path %>
</div>

app/views/animals/show.html.erb
<p style="color: green"><%= notice %></p>


<%= render @animal %>  


<div>
  <%= link_to "Editar 'animal'", edit_animal_path(@animal) %> |
  <%= link_to "Voltar para 'animais'", animals_path %>
  <%= button_to "Deletar 'animal'", @animal, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IbcApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheets" href="ibc_app/app/assets/stylesheets/stylesheets.css">
  </head>

  <body>
    <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>